/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utils;

import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author ADMIN
 */
public class BookShell extends javax.swing.JPanel {

    /**
     * Creates new form BookShell
     */
    
    public BookShell(Book book) {
        initComponents();
        this.setSize(151, 256);
        System.out.println(imageLabel.getWidth());
        this.imageLabel.setIcon( new ImageIcon(ImageUtils.getImage(book.getImgPath(), 
                150, 160)));
        this.nameLabel.setText(book.getTen());
        this.publisherLabel.setText("NXB: " + book.getNhaXuatBan());
        this.priceLabel.setText("Giá bán: " + Double.toString(book.getGia()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        publisherLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(imageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 160));

        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setText("Name");
        add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 166, 150, 20));

        publisherLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        publisherLabel.setText("Publisher");
        add(publisherLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 190, 150, -1));

        priceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        priceLabel.setText("Price: ");
        add(priceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 210, 150, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel publisherLabel;
    // End of variables declaration//GEN-END:variables
    

}
