/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utils;

import java.util.ArrayList;

/**
 *
 * @author ADMIN
 */
public class CatalogPanel extends javax.swing.JPanel {
    private ArrayList<Book> bookList;
    private ArrayList<BookDisplayShell> bookDisplayList = new ArrayList<BookDisplayShell>();
    /**
     * Creates new form CatalogPanel
     */
    
    private ArrayList<Book> initBookList(){
        ArrayList <Book> arr = new ArrayList<Book>();
        arr.add(new Book(10, "Sach giao khoa1", "Kim dong", 2017, 30000, "resources/img/book_icon.png"));
        arr.add(new Book(10, "Sach giao khoa2", "Kim dong", 2017, 30000, "resources/img/book_icon.png"));
        arr.add(new Book(10, "Sach giao khoa3", "Kim dong", 2017, 30000, "resources/img/book_icon.png"));
        arr.add(new Book(10, "Sach giao khoa4", "Kim dong", 2017, 30000, "resources/img/book_icon.png"));
        arr.add(new Book(10, "Sach giao khoa5", "Kim dong", 2017, 30000, "resources/img/book_icon.png"));
        arr.add(new Book(10, "Sach giao khoa6", "Kim dong", 2017, 30000, "resources/img/book_icon.png"));
        arr.add(new Book(10, "Sach giao khoa7", "Kim dong", 2017, 30000, "resources/img/book_icon.png"));
        arr.add(new Book(10, "Sach giao khoa8", "Kim dong", 2017, 30000, "resources/img/book_icon.png"));
        arr.add(new Book(10, "Sach giao khoa9", "Kim dong", 2017, 30000, "resources/img/book_icon.png"));
        arr.add(new Book(10, "Sach giao khoa10", "Kim dong", 2017, 30000, "resources/img/book_icon.png"));
        return arr;
    }
    
    public void updateBookDisplayList(ArrayList<Book> bookList){
        bookDisplayList.clear();
        this.displayArea.removeAll();
        for (Book book : bookList){
            bookDisplayList.add(new BookDisplayShell(book));
        }
        updateBookDisplayList();
        this.updateUI();
    }
    
    private void initBookDisplayList(){
        for (Book book : bookList){
            bookDisplayList.add(new BookDisplayShell(book));
        }
        
    }
    
    private void updateBookDisplayList(){
        for (int i = 0; i<Math.min(9, bookDisplayList.size()); i++){
            this.displayArea.add(bookDisplayList.get(i));
        }
    }
    public CatalogPanel() {
        initComponents();
        bookList = initBookList();
        initBookDisplayList();
        for (int i = 0; i<Math.min(9, bookDisplayList.size()); i++){
            this.displayArea.add(bookDisplayList.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        displayArea = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        displayArea.setPreferredSize(new java.awt.Dimension(600, 1600));
        displayArea.setLayout(new java.awt.GridLayout(3, 3, 3, 3));
        jPanel1.add(displayArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 630, 630));

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 1, 26)); // NOI18N
        jLabel14.setText("Manga Book:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, -1));

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, 80, -1));

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        jPanel1.add(nextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        
    }//GEN-LAST:event_nextButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JPanel displayArea;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nextButton;
    // End of variables declaration//GEN-END:variables
}
