package utils;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ADMIN
 */
public class FormNhapDuLieu extends javax.swing.JFrame {

    /**
     * Creates new form FormNhapDuLieu
     */
    public void write_image_to_source(String absPath, String fileName) throws IOException {
        String resultPath = "resources/img/" + fileName;
        FileOutputStream fos = new FileOutputStream(new java.io.File(resultPath));
        FileInputStream fis = new FileInputStream(new java.io.File(absPath));
        byte[] buf = new byte[1024];    
        int hasRead = 0;
        while((hasRead = fis.read(buf)) > 0){
            fos.write(buf, 0, hasRead);
        }
        fis.close();
        fos.close();
        this.imgPath = resultPath;
    }
    
    public void write_to_database() throws ClassNotFoundException, SQLException {
        Connection connect = null;
        connect = MySQLConnUtils.getMySQLConnection();

        Statement statement = connect.createStatement();

        String name = this.nameField.getText();
        String publisher = this.publisherField.getText();
        double price = Double.parseDouble(this.priceField.getText());
        String discription = this.discriptionField.getText();
        String typeStr = (String) this.type.getSelectedItem();
        System.out.println(typeStr);
        // imgPath has been gained when in writeImageToSource

        String sqlQuery = "Insert Into books (bo_name, bo_publisher, pricel, year, image, description, type, amount)"
                + " Values ('" + name + "', '" + publisher + "', " + Double.toString(price) + ", 2019, '" + imgPath
                + "', '" + discription + "', '" + typeStr + "', 100)";
        
        System.out.println(sqlQuery);

        statement.executeUpdate(sqlQuery);
    }
    
    public FormNhapDuLieu() {
        initComponents();
        this.type.addItem("Best Seller");
        this.type.addItem("Life");
        this.type.addItem("Literature");
        this.type.addItem("Math");
        this.type.addItem("Programing");
        this.imageChooser = new JFileChooser();
        imgPathButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int returnVal = imageChooser.showOpenDialog(imgPathButton1);
                if (returnVal == JFileChooser.APPROVE_OPTION){
                    String fileName = imageChooser.getSelectedFile().getName();
                    String filePath = imageChooser.getSelectedFile().getPath();
                    try {
                        write_image_to_source(filePath, fileName);
                    } catch (IOException ex) {
                        Logger.getLogger(FormNhapDuLieu.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LB_Ten = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        LB_Ten1 = new javax.swing.JLabel();
        publisherField = new javax.swing.JTextField();
        LB_Ten2 = new javax.swing.JLabel();
        LB_Ten4 = new javax.swing.JLabel();
        authorField = new javax.swing.JTextField();
        LB_Ten3 = new javax.swing.JLabel();
        discriptionField = new javax.swing.JTextField();
        priceField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        imgPathButton1 = new javax.swing.JButton();
        type = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LB_Ten.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LB_Ten.setText("Giá:");
        jPanel1.add(LB_Ten, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 90, 50));

        nameField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 230, 50));

        LB_Ten1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LB_Ten1.setText("Nhà Xuất Bản:");
        jPanel1.add(LB_Ten1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 130, 50));

        publisherField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(publisherField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 230, 50));

        LB_Ten2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LB_Ten2.setText("Tác Giả:");
        jPanel1.add(LB_Ten2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 130, 50));

        LB_Ten4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LB_Ten4.setText("Tên Sách:");
        jPanel1.add(LB_Ten4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 110, 50));

        authorField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(authorField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 230, 50));

        LB_Ten3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LB_Ten3.setText("Miêu Tả:");
        jPanel1.add(LB_Ten3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 130, 50));

        discriptionField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        discriptionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discriptionFieldActionPerformed(evt);
            }
        });
        jPanel1.add(discriptionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 370, 90));
        jPanel1.add(priceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 102, 280, 50));

        submitButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        submitButton.setText("Gửi");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, 110, 50));

        imgPathButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        imgPathButton1.setText("Chọn Ảnh");
        imgPathButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imgPathButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(imgPathButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 110, 50));

        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });
        jPanel1.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 90, 50));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 204));
        jLabel2.setText("Nhập Dữ Liệu");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 340, 70));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Documents\\NetBeansProjects\\MavenBookStore\\resources\\img\\BGNhapForm.gif")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 740, 440));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("sdd");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 820));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void discriptionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discriptionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_discriptionFieldActionPerformed

    private void imgPathButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imgPathButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imgPathButton1ActionPerformed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        try {
            write_to_database();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FormNhapDuLieu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FormNhapDuLieu.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_submitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormNhapDuLieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormNhapDuLieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormNhapDuLieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormNhapDuLieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormNhapDuLieu form = new FormNhapDuLieu();
                form.show();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LB_Ten;
    private javax.swing.JLabel LB_Ten1;
    private javax.swing.JLabel LB_Ten2;
    private javax.swing.JLabel LB_Ten3;
    private javax.swing.JLabel LB_Ten4;
    private javax.swing.JTextField authorField;
    private javax.swing.JTextField discriptionField;
    private javax.swing.JButton imgPathButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField priceField;
    private javax.swing.JTextField publisherField;
    private javax.swing.JButton submitButton;
    private javax.swing.JComboBox type;
    // End of variables declaration//GEN-END:variables
    private JFileChooser imageChooser;
    private String imgPath;
}
