/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mavenbookstore.panel;

import com.mycompany.mavenbookstore.mainclass.Book;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import com.mycompany.mavenbookstore.utils.ImageUtils;

/**
 *
 * @author ADMIN
 */
public class ContentPanel extends javax.swing.JPanel {
    Book book;

    public Book getBook() {
        return book;
    }
    private boolean added;
    
    public boolean isAdded(){
        return this.added;
    }
    public void setAdded(boolean added){
        this.added = added;
    }
    /**
     * Creates new form ContentPanel
     */
    public ContentPanel() {
        initComponents();
    }
    
    public ContentPanel(Book book){
        initComponents();
        this.book = book;
        
        this.imgLabel.setIcon(new ImageIcon(ImageUtils.getImage(book.getImgPath(), 280, 360)));
        this.nameLabel.setText("Name: " + book.getTen());
        this.authorLabel.setText("Publisher: " + book.getNhaXuatBan());
        this.coverLabel.setIcon(new ImageIcon(ImageUtils.getImage("resources/img/naruto_cover.jpg", 1330, 380)));
        this.descriptionLabel.setText(book.getDescription());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        authorLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        imgLabel = new javax.swing.JLabel();
        coverLabel = new javax.swing.JLabel();
        costLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1300, 1000));

        jPanel2.setMinimumSize(new java.awt.Dimension(1330, 1000));
        jPanel2.setPreferredSize(new java.awt.Dimension(1330, 1000));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        addButton.setText("Add to Cart");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel2.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, 130, 50));

        authorLabel.setBackground(new java.awt.Color(0, 0, 0));
        authorLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        authorLabel.setText("Author:");
        jPanel2.add(authorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 210, 30));

        nameLabel.setBackground(new java.awt.Color(0, 0, 0));
        nameLabel.setFont(new java.awt.Font(".VnArial", 1, 36)); // NOI18N
        nameLabel.setText("NARUTO");
        jPanel2.add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 440, 50));

        imgLabel.setBackground(new java.awt.Color(255, 255, 255));
        imgLabel.setForeground(new java.awt.Color(255, 255, 255));
        imgLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(imgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 280, 360));

        coverLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(coverLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1330, 380));

        costLabel.setBackground(new java.awt.Color(0, 0, 0));
        costLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        costLabel.setText("Cost: ");
        jPanel2.add(costLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 500, 210, 30));

        descriptionLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(descriptionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 660, 1050, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1330, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel authorLabel;
    private javax.swing.JLabel costLabel;
    private javax.swing.JLabel coverLabel;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables

    public JButton getAddButton() {
        return addButton;
    }
}
